### ISSUE TITLE
Enable multiple inputs and outputs CustomPyOp effectual

### ISSUE THREAD

**Issue by raymon-tian** [microsoft/ort-customops#51]
Hi, thanks for your great work.

In the https://github.com/microsoft/ort-customops/blob/main/test/test_torch_ops.py, the custom onnxruntime python operator with single input and output works well.

But  if I twist the operator into the one with multiple inputs  and outputs, it doesn't work.

Thus, How can I enable multiple inputs and outputs CustomPyOp effectual ?

thanks

**Comment by wenbingl** [comment]
The multiple inputs and outputs should be supported already, Can you share your code to demo what the error is?

**Comment by raymon-tian** [comment]
@wenbingl Thanks for your reply. It's my fault. I have made it. Thanks.
